#
# Copyright 2008-2011 Marvell Semiconductor, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# Version 2 as published by the Free Software Foundation.
#

obj-$(CONFIG_SYS_MCK5_DDR)	+= mck5.o
obj-$(CONFIG_SYS_MCK4_DDR)	+= mck4.o
obj-$(CONFIG_SYS_MCK6_DDR)	+= mck6.o
