#
# Copyright (C) 2012 Samsung Electronics
# Lukasz Majewski <l.majewski@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_POWER_FG_MAX17042) += fg_max17042.o
obj-$(CONFIG_POWER_88PM830) += fg_88pm830.o
obj-$(CONFIG_POWER_88PM886) += fg_88pm88x.o
obj-$(CONFIG_POWER_88PM880) += fg_88pm88x.o
