#
# (C) Copyright 2016
# Marvell Semiconductor <www.marvell.com>
# Written-by: zhxihu <zhxihu@marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

OBJS-libbvb += bvb_property.o bvb_rsa.o bvb_sha256.o bvb_sha512.o bvb_sysdeps_stub.o bvb_util.o bvb_verify.o

obj-$(CONFIG_MV_BVB) += $(OBJS-libbvb)
