#
# (C) Copyright 2012
# Marvell Semiconductor <www.marvell.com>
# Written-by: Xiang Wang <wangx@marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= emmd_rsv.o

obj-$(CONFIG_EEPROM_34XX02) += eeprom_34xx02.o
obj-$(CONFIG_GENERIC_MMC) += mv_recovery.o
obj-$(CONFIG_LEDS_88PM828X) += leds-88pm828x.o
obj-$(CONFIG_LEDS_LM3532) += leds-lm3532.o
obj-$(CONFIG_MMP_DISP) += panel.o
obj-$(CONFIG_MRVL_BOOT) += mv_boot.o
obj-$(CONFIG_MULTIPLE_SLOTS) += bootctrl.o
obj-$(CONFIG_RAMDUMP) += ramdump_service.o
obj-$(CONFIG_SQU_DEBUG_SUPPORT) += squ_debug.o
obj-$(CONFIG_POWER_OFF_CHARGE) += charge.o
obj-$(CONFIG_PERSIST_DATA) += persistdata.o
obj-$(CONFIG_FASTBOOT_BVB) += bvb_mmc.o

obj-y += mv_cp.o tim.o
