#
# Copyright (C) 2012 Samsung Electronics
# Lukasz Majewski <l.majewski@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_POWER_MAX8998) += pmic_max8998.o
obj-$(CONFIG_POWER_MAX8997) += pmic_max8997.o
obj-$(CONFIG_POWER_MUIC_MAX8997) += muic_max8997.o
obj-$(CONFIG_POWER_MAX77686) += pmic_max77686.o
obj-$(CONFIG_POWER_TPS65217) += pmic_tps65217.o
obj-$(CONFIG_POWER_TPS65910) += pmic_tps65910.o
obj-$(CONFIG_POWER_88PM820) += pmic_88pm820.o pmic_mrvl_common.o
obj-$(CONFIG_POWER_88PM800) += pmic_88pm800.o pmic_mrvl_common.o
obj-$(CONFIG_POWER_88PM860) += pmic_88pm860.o pmic_mrvl_common.o
obj-$(CONFIG_POWER_88PM886) += pmic_88pm886.o pmic_mrvl_common.o
obj-$(CONFIG_POWER_88PM830) += pmic_88pm830.o
obj-$(CONFIG_POWER_88PM880) += pmic_88pm880.o pmic_mrvl_common.o
