#
# Copyright (C) 2012 Samsung Electronics
# Lukasz Majewski <l.majewski@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_POWER_BATTERY_TRATS) += bat_trats.o
obj-$(CONFIG_POWER_BATTERY_TRATS2) += bat_trats2.o
obj-$(CONFIG_POWER_88PM830) += bat_88pm830.o
obj-$(CONFIG_POWER_88PM886) += bat_88pm88x.o
obj-$(CONFIG_POWER_88PM880) += bat_88pm88x.o
